/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaanpr;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaanpr.imageanalysis.CarSnapshot;
import javaanpr.intelligence.Intelligence;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author EMAXX-A55-FM2
 */
public class CamCap extends javax.swing.JFrame {

//    private Dimension ds = new Dimension(450, 360);
    private Dimension ds = new Dimension(400, 300);
    private Dimension cs = WebcamResolution.VGA.getSize();
    private Webcam webcam = Webcam.getDefault();
    private WebcamPanel webcamPanel = new WebcamPanel(webcam, ds, false);

    /**
     * Creates new form CamCap
     */
    public CamCap() {
        initComponents();
        webcam.setViewSize(cs);
        webcamPanel.setFillArea(true);
        panelCamera.setLayout(new FlowLayout());
        panelCamera.add(webcamPanel);
        Timer t = new Timer();
        CapturePlateNumberServiceTimerTask captureService = new CapturePlateNumberServiceTimerTask();
        captureService.setWebCam(webcam);
        captureService.setLabelPlateNumber(plateNumberLabel);
        t.schedule(captureService, 2000,2000);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBtn = new javax.swing.JButton();
        captureBtn = new javax.swing.JButton();
        panelCamera = new javax.swing.JPanel();
        recognizeBtn = new javax.swing.JButton();
        plateNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo ANPR - Image Processing");

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        captureBtn.setText("Capture");
        captureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureBtnActionPerformed(evt);
            }
        });

        panelCamera.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelCameraLayout = new javax.swing.GroupLayout(panelCamera);
        panelCamera.setLayout(panelCameraLayout);
        panelCameraLayout.setHorizontalGroup(
            panelCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCameraLayout.setVerticalGroup(
            panelCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        recognizeBtn.setText("Recognize");
        recognizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recognizeBtnActionPerformed(evt);
            }
        });

        plateNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plateNumberLabel.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plateNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(startBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(captureBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recognizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn)
                    .addComponent(captureBtn)
                    .addComponent(recognizeBtn)
                    .addComponent(plateNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        Thread th = new Thread(new Runnable() {
            @Override
            public void run() {
                webcamPanel.start();
            }
        });
        th.setDaemon(true);
        th.start();
    }//GEN-LAST:event_startBtnActionPerformed

    private void captureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureBtnActionPerformed

        File fileCaptured = new File(String.format("capture-%d.jpg", System.currentTimeMillis()));
        try {
            ImageIO.write(webcam.getImage(), "JPG", fileCaptured);
            JOptionPane.showMessageDialog(null, "Saved!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong");
            Logger.getLogger(CamCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_captureBtnActionPerformed

    private void recognizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recognizeBtnActionPerformed
 //get current image 
        CarSnapshot carSnap = new CarSnapshot(webcam.getImage());
        String numberPlate = null;
        Intelligence intel = null;
        try {
            intel = new Intelligence(false);
        } catch (Exception ex) {
            Logger.getLogger(CamCap.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //ask anpr if it can recognize
            numberPlate = intel.recognize(carSnap);
            //print result to output
        } catch (Exception ex) {
            Logger.getLogger(CamCap.class.getName()).log(Level.SEVERE, null, ex);
        }
//        JOptionPane.showMessageDialog(null, numberPlate);
        System.out.println(numberPlate);
    }//GEN-LAST:event_recognizeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CamCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CamCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CamCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CamCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CamCap camCap = new CamCap();
                camCap.setResizable(false);
                camCap.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton captureBtn;
    private javax.swing.JPanel panelCamera;
    private javax.swing.JLabel plateNumberLabel;
    private javax.swing.JButton recognizeBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
